### ISSUE TITLE
7/12, todo

### ISSUE THREAD

**Issue by xoansdhkd** [Douzone2nd-Team2/finalProject#118]
- [ ] 예약 중 상태 관리 - able N들은 20분 뒤에 자동으로 삭제
- [ ] 예약 완료 페이지 이동 - 메인으로
- [ ] 마이페이지 예약 현황 조회 -> 누르면 예약 상세 페이지로 이동
- [ ] 예약 상세 페이지에서 예약 취소 기능 구현
